# Generated by Django 6.0.3 on 2026-03-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0004_remove_project_created_at_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived'), ('overdue', 'Overdue')], default='active', max_length=20),
        ),
    ]
