# Generated by Django 6.0.3 on 2026-04-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMApp', '0008_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
